# permissions for end users to view humiousers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humiouser-viewer-role
rules:
- apiGroups:
  - core.humio.com
  resources:
  - humiousers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.humio.com
  resources:
  - humiousers/status
  verbs:
  - get
