apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    productID: "none"
    productName: "humio-operator"
    productVersion: {{ .Values.operator.image.tag | quote }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "operator.chart" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        productID: "none"
        productName: "humio-operator"
        productVersion: {{ .Values.operator.image.tag | quote }}
{{- if .Values.operator.podAnnotations }}
        {{- toYaml .Values.operator.podAnnotations | nindent 8 }}
{{- end }}
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ template "operator.chart" . }}
    spec:
{{- with .Values.operator.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      serviceAccountName: {{ include "operator.fullname" . }}
      containers:
      - name: humio-operator
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.operator.watchNamespaces | join "," | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: USE_CERTMANAGER
          value: {{ .Values.certmanager | quote }}
{{- if .Values.openshift }}
        - name: OPENSHIFT_SCC_NAME
          value: {{ include "operator.fullname" . }}-{{ default "default" .Release.Namespace }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
{{- with .Values.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
